//
//  LineUpsPresenter.swift
//  storybook
//
//  Created by Daniel Cabrera Entelgy on 31/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum LineUpsPresenterViewState {
}

protocol LineUpsPresentationLogic: AnyObject {
    var viewController: LineUpsDisplayLogic? { get set }
    var router: LineUpsRoutingLogic? { get set }
    func viewDidLoad()
    func didHaveAnError(with message: String)
}

class LineUpsPresenter: LineUpsPresentationLogic {
    weak var viewController: LineUpsDisplayLogic?
    var router: LineUpsRoutingLogic?

    func viewDidLoad() {
    }

    func didHaveAnError(with message: String) {
        router?.showError(with: message)
    }
}
