# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'storybook' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'KaizenSDK', :git => 'https://github.com/danielcPrettytechnical/KaizenSDK.git', :tag => '1.1.0'


  target 'storybookTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'storybookUITests' do
    # Pods for testing
  end

end
