//
//  MainModels.swift
//  storybook
//
//  Created by Daniel Cabrera Entelgy on 31/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
enum MainComponentsValue: CaseIterable {
    case pitchComponent
    case statsComponent
    case summaryComponent
    case lineUpsComponent
    case standingsComponent
    case matchIncidentsComponent
    case momentumComponent
    case matchDetailTabsView
    case statisticsCarousel
}

extension MainComponentsValue {
    var componentTitle: String {
        switch self {
        case .pitchComponent:
            return "Pitch Component"
        case .statsComponent:
            return "Stats Component"
        case .summaryComponent:
            return "Summary Component"
        case .lineUpsComponent:
            return "Line Ups Component"
        case .standingsComponent:
            return "Standings Component"
        case .matchIncidentsComponent:
            return "Match Incidents Component"
        case .momentumComponent:
            return "Momentum Component"
        case .matchDetailTabsView:
            return "Match Detail View"
        case .statisticsCarousel:
            return "Statistics Carousel"
        }
    }
}
