//
//  SummaryModels.swift
//  storybook
//
//  Created by Daniel Cabrera Entelgy on 31/03/2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//
struct SummaryComponentsValue {
}
